Feat/episode 에피소드 생성,조회,수정기능추가 및 final선언 및 테스트코드추가
nbcamp-spring-junwoo/orz pull request #29
Opened 2024-04-02 17:16 UTC by ersesd

## 변경사항

### 변경의 종류 (여러 가지 선택 가능)

- [x] 새로운 기능
- [ ] 버그 수정
- [ ] 문서 업데이트
- [x] 테스트 추가
- [ ] 기타(설명 추가)

---

## 체크리스트

- [x] ERD설계와 API설계를 잘 적용하여 개발하였는가?
- [x] 서비스 테스트의 커버리지가 80% 이상인가?
- [x] 코딩 컨벤션을 준수하였는가?
- [x] 예외 처리가 잘 되어 있는가?
- [x] 커밋 메시지를 컨벤션에 맞게 작성 하였는가?

2024-04-02 17:46 UTC, tktcod commented on src/main/java/com/junwoo/ott/domain/episode/controller/EpisodeController.java
> +    }
매개변수는 dto 하나만 들어갈수 있게 videoId, title, releasedAt을 합쳐서  EpisodeCreateRequestDto으로 만들어주세요

2024-04-02 17:47 UTC, tktcod commented on src/main/java/com/junwoo/ott/domain/episode/controller/EpisodeController.java
> +
개행이 많습니다

2024-04-03 00:19 UTC, ersesd commented on src/main/java/com/junwoo/ott/domain/episode/controller/EpisodeController.java
> +    }
네 수정했습니다!

2024-04-03 00:54 UTC, ruh0n approved these changes
배우고갑니다. LGTM

2024-04-03 00:54 UTC, ruh0n commented on src/main/java/com/junwoo/ott/domain/episode/repository/EpisodeCustomRepositoryImpl.java
> +@RequiredArgsConstructor
순서가 바뀐 것 같습니다.

2024-04-03 01:36 UTC, ersesd commented on src/main/java/com/junwoo/ott/domain/episode/repository/EpisodeCustomRepositoryImpl.java
> +@RequiredArgsConstructor
네 수정했습니다!

2024-04-03 04:26 UTC, gloz0315 approved these changes
LGTM

2024-04-03 10:38 UTC, ruh0n requested changes

2024-04-03 10:38 UTC, ruh0n commented on src/main/java/com/junwoo/ott/domain/episode/controller/EpisodeController.java
> +    @DeleteMapping("/episodeId}")
괄호가 하나 빠졌습니다.

2024-04-03 10:53 UTC, ersesd commented on src/main/java/com/junwoo/ott/domain/episode/controller/EpisodeController.java
> +    @DeleteMapping("/episodeId}")
수정했습니다!

2024-04-03 11:22 UTC, tktcod approved these changes
LGTM 고생하셨네요

2024-04-03 11:43 UTC, ruh0n approved these changes

2024-04-03 13:09 UTC, merged