Feat/database CQRS 적용
nbcamp-spring-junwoo/orz pull request #67
Opened 2024-04-23 07:47 UTC by tktcod

## 변경사항

배포 스크립트 추가, 데이터베이스 CQRS 적용, Health Check 응답 추가

### 변경의 종류 (여러 가지 선택 가능)

- [x] 새로운 기능
- [ ] 버그 수정
- [ ] 문서 업데이트
- [ ] 테스트 추가
- [ ] 기타(설명 추가)

---

## 체크리스트

- [x] ERD설계와 API설계를 잘 적용하여 개발하였는가?
- [x] 서비스 테스트의 커버리지가 80% 이상인가?
- [x] 코딩 컨벤션을 준수하였는가?
- [x] 예외 처리가 잘 되어 있는가?
- [x] 커밋 메시지를 컨벤션에 맞게 작성 하였는가?

2024-04-23 10:26 UTC, gloz0315 approved these changes
LGTM

2024-04-23 10:27 UTC, ruh0n requested changes

2024-04-23 10:27 UTC, ruh0n commented on .github/workflows/deploy.yml
![image](https://github.com/nbcamp-spring-junwoo/orz/assets/48433827/ff64c342-a5e9-4571-a954-1c327bbc4ffa)

워닝 해결 부탁드립니다.

2024-04-23 10:43 UTC, devJWL approved these changes
LGTM

2024-04-24 01:19 UTC, ruh0n approved these changes
LGTM

2024-04-24 01:31 UTC, merged